CC = gcc
CFLAGS = -Wall -Wextra -pedantic -std=c99

SRC_DIR = src
BUILD_DIR = build
BIN_DIR = bin

# find all .c files automatically
SRCS := $(wildcard $(SRC_DIR)/*.c)

# convert them into .o files inside bin/
OBJS := $(patsubst $(SRC_DIR)/%.c,$(BUILD_DIR)/%.o,$(SRCS))

TARGET = $(BIN_DIR)/leyo.exe

# default target
all: $(BUILD_DIR) $(TARGET)

# create build directory
$(BUILD_DIR):
	mkdir $(BUILD_DIR)

$(BIN_DIR):
	mkdir $(BIN_DIR)


# link step
$(TARGET): $(OBJS)
	$(CC) $(CFLAGS) $^ -o $@

# compile step (automatic rule for all .c files)
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	$(CC) $(CFLAGS) -c $< -o $@

# run program
run: all
	$(TARGET)

# clean build files
clean:
	del /Q $(BUILD_DIR)\*.o 2> nul
	del /Q $(BIN_DIR)\*.exe 2> nul

.PHONY: all clean run