param(
    [string]$Exe = ".\bin\leyo.exe",
    [string]$Source = ".\test.leyo"
)

$ErrorActionPreference = "Stop"

function Write-Step($message) {
    Write-Host "[TEST] $message"
}

if (-not (Test-Path $Exe)) {
    Write-Step "Executable not found, building first"
    & make | Out-Host
    if ($LASTEXITCODE -ne 0) {
        throw "Build failed"
    }
}

$tempDir = Join-Path $env:TEMP ("leyo-smoke-" + [guid]::NewGuid().ToString("N"))
New-Item -ItemType Directory -Path $tempDir | Out-Null

$output = Join-Path $tempDir "smoke.lybc"

try {
    Write-Step "Building $Source"
    & $Exe build $Source $output | Out-Host
    if ($LASTEXITCODE -ne 0) {
        throw "Build command failed"
    }

    if (-not (Test-Path $output)) {
        throw "Build did not produce output"
    }

    Write-Step "Running generated bytecode"
    & $Exe run $output | Out-Host
    if ($LASTEXITCODE -ne 0) {
        throw "Run command failed"
    }

    Write-Step "Disassembling bytecode"
    & $Exe disassemble $output | Out-Host
    if ($LASTEXITCODE -ne 0) {
        throw "Disassemble command failed"
    }

    Write-Step "Smoke test passed"
}
finally {
    Remove-Item -LiteralPath $tempDir -Recurse -Force
}
