#ifndef ERR_CODES_H
#define ERR_CODES_H

#include <stdbool.h>

typedef enum {
    // File
    ERR_FILE_OPEN_ERROR,
    ERR_FILE_TOO_SMALL,
    ERR_FILE_CANNOT_DEL,
    ERR_FILE_OPEN_WARN,
    ERR_FILE_WRITE_ERROR,
    ERR_FILE_TEMP_NOT_AVAILABLE,

    // CLI
    ERR_MISSING_SOURCE_FILE,
    ERR_MISSING_INPUT_FILE,
    ERR_RM_COMMAND_UNKOWN,
    ERR_UNKNOWN_CLI_ARG,

    // Lexer
    ERR_LEX_UNTERMINATED_STR_LIT,
    ERR_LEX_INVALID_CHAR,
    ERR_LEX_OUT_OF_MEMORY,
    ERR_LEX_INVALID_NUM,

    // Parser
    ERR_PARSER_EXPECTED_IDENT,
    ERR_PARSER_EXPECTED_TOKEN,
    ERR_PARSER_NO_SEMICOLON,

    ERR_PARSER_VAR_NOT_DEFINED,
    ERR_PARSER_VAR_PERVIOUSLY_DEFINED,
    ERR_PARSER_FUNC_NOT_DEFINED,
    ERR_PARSER_FUNC_PERVIOUSLY_DEFINED,

    ERR_PARSER_CANNOT_SHADOW_KW,
    ERR_PARSER_TYPE_CONFLICT_EXPR,
    ERR_PARSER_UNKOWN_OPERATOR,
    ERR_PARSER_ATOM_UNKOWN,
    ERR_PARSER_UNKOWN_IDENT_STMT,
    ERR_PARSER_UNKOWN_STMT,
    ERR_PARSER_UNKOWN_NATIVE,

    ERR_PARSER_NO_OPEN_TYPE_BRACKET,
    ERR_PARSER_NO_CLOSE_TYPE_BRACKET,

    ERR_PARSER_MODULE_PREVIOUSLY_LOADED,
    ERR_PARSER_MODULE_CANNOT_OPEN,
    ERR_PARSER_LEXER_FAILURE_CAUGHT,

    ERR_PARSER_INTO_ENDOFSTREAM,
    ERR_PARSER_INTO_STARTOFSTREAM,
    ERR_PARSER_UNEXPECTED_STATE,
    ERR_PARSER_STALLED,
    ERR_PARSER_CANNOT_ALLOCATE,
    ERR_PARSER_BYTE_OVERFLOW,
    ERR_PARSER_OUT_OF_BOUNDS,
    ERR_PARSER_NO_ENTRY_POINT,

    // Bytecode
    ERR_INVALID_BYTECODE_HEADER,
    ERR_INVALID_BYTECODE,
    ERR_CANNOT_READ_BYTECODE,
    ERR_WARN_DIFFERERENT_VERSIONS,

    // Virtual Machine
    ERR_VM_UNDERFLOW,
    ERR_VM_INVALID_BINARY_OP,
    ERR_VM_CANNOT_DECODE_CONST_POOL,
    ERR_VM_CANNOT_ALLOCATE,
    ERR_VM_INVALID_CONST_POOL,
    ERR_VM_INVALID_JUMP,
    ERR_VM_GLOBAL_SLOT_OUT_OF_RANGE,
    ERR_VM_CONST_OUT_OF_RANGE,
    ERR_VM_UNKOWN_NATIVE_COMMAND,
    ERR_VM_TEXT_NUM_TYPE_CALC,
    ERR_VM_TEXT_CALC_UNSUPPORTED,
    ERR_VM_UNEXPECTED_EXIT,

    // Internal
    ERR_LYST_FAILED_LOAD,
    ERR_UNKOWN_GLOBAL_FLAG,
    ERR_NOT_IMPLEMENTED_YET,
    ERR_NOT_IMPLEMENTED,

    ERR_AMOUNT
} ErrorCode;

typedef struct {
    ErrorCode ec; // like ERR_ZERO_DIV
    char *name; // like V001
    char *msg; // like Cannot divide by zero
    bool fatal; // if fatal or recoverable
} Error;

typedef enum {
    WF_VM,
    WF_BUILD,
    WF_GENERAL,
} WhereFrom;

typedef struct {
    ErrorCode ec; // like ERR_ZERO_DIV
    int line;
    int column;
    char filename[512];
    WhereFrom wf;
} RaisedError;

extern const Error errorTable[];
extern const unsigned int errorTableAmt;

#endif