#include <stdio.h>
#include <stdlib.h>
#include "../include/errors.h"
#include <string.h>

#ifdef _WIN32
    #include <windows.h>
#else
    #include <unistd.h>
    #include <limits.h>
    #include <sys/stat.h>
#endif

static char tmpFolderName[1024];

#ifdef _WIN32
static int runCommand(const char *cmd) {
    return system(cmd);
}
#else
static int runCommand(const char *cmd) {
    int rc = system(cmd);
    if (WIFEXITED(rc))
        return WEXITSTATUS(rc);
    return 1;
}
#endif

static void writeTest(const char *str);

static int createTmpFolder(void) {
    writeTest("Creating temporary workspace");
    #ifdef _WIN32
        char tempPath[MAX_PATH];
        char uniquePath[MAX_PATH];

        if (!GetTempPathA(MAX_PATH, tempPath)) {
            fprintf(stderr, "GetTempPath failed\n");
            return 1;
        }

        if (!GetTempFileNameA(tempPath, "LYO", 0, uniquePath)) {
            fprintf(stderr, "GetTempFileName failed\n");
            return 1;
        }

        DeleteFileA(uniquePath);

        if (!CreateDirectoryA(uniquePath, NULL)) {
            fprintf(stderr, "CreateDirectory failed: %lu\n", GetLastError());
            return 1;
        }

        snprintf(tmpFolderName, sizeof(tmpFolderName), "%s", uniquePath);
        logController("Temporary workspace created");
        return 0;

    #else
        char template[] = "/tmp/leyo-smoke-XXXXXX";

        char *dir = mkdtemp(template);
        if (!dir) {
            perror("mkdtemp");
            return 1;
        }

        snprintf(tmpFolderName, sizeof(tmpFolderName), "%s", dir);
        logController("Temporary workspace created");
        return 0;
    #endif
}

static void destroyTmpFolder(void) {
    logController("Destroying temporary workspace");
    #ifdef _WIN32
        char sourceFile[2048];
        char outputFile[2048];

        snprintf(sourceFile, sizeof(sourceFile),
                "%s\\test.leyo", tmpFolderName);

        snprintf(outputFile, sizeof(outputFile),
                "%s\\smoke.lybc", tmpFolderName);

        DeleteFileA(sourceFile);
        DeleteFileA(outputFile);
        RemoveDirectoryA(tmpFolderName);

    #else
        char sourceFile[2048];
        char outputFile[2048];

        snprintf(sourceFile, sizeof(sourceFile),
                "%s/test.leyo", tmpFolderName);

        snprintf(outputFile, sizeof(outputFile),
                "%s/smoke.lybc", tmpFolderName);

        unlink(sourceFile);
        unlink(outputFile);
        rmdir(tmpFolderName);
    #endif
}

static void writeTest(const char *str) {
    printf("[TEST] %s\n", str);
    logController(str);
}

int testLeyo(const char *leyoBin) {
    int r = 1;
    FILE *f = NULL;

    char sourceFile[2048];
    char outputFile[2048];
    char cmd[8192];

    writeTest("Starting Smoke Test");

    /*
     * Nested Leyo commands need to rotate logs on startup.
     * Close the parent logger so the child processes can archive
     * the current log without a Windows file-lock conflict.
     */
    closeLog();

    if (createTmpFolder())
        goto cleanup;

    #ifdef _WIN32
        snprintf(sourceFile, sizeof(sourceFile),
                "%s\\test.leyo", tmpFolderName);

        snprintf(outputFile, sizeof(outputFile),
                "%s\\smoke.lybc", tmpFolderName);
    #else
        snprintf(sourceFile, sizeof(sourceFile),
                "%s/test.leyo", tmpFolderName);

        snprintf(outputFile, sizeof(outputFile),
                "%s/smoke.lybc", tmpFolderName);
    #endif

    writeTest("Creating source file");

    f = fopen(sourceFile, "w");
    if (!f) {
        fprintf(stderr, "Failed to create source file\n");
        goto cleanup;
    }

    fputs("int a = 5;\n", f);
    fclose(f);
    f = NULL;

    writeTest("Building source");

    snprintf(cmd, sizeof(cmd),
             "%s build \"%s\" -o \"%s\"",
             leyoBin, sourceFile, outputFile);

    if (runCommand(cmd)) {
        fprintf(stderr, "Build command failed\n");
        goto cleanup;
    }

    f = fopen(outputFile, "rb");
    if (!f) {
        fprintf(stderr, "Build did not produce output\n");
        goto cleanup;
    }
    fclose(f);
    f = NULL;

    writeTest("Running generated bytecode");

    snprintf(cmd, sizeof(cmd),
             "%s run %s",
             leyoBin, outputFile);

    if (runCommand(cmd)) {
        fprintf(stderr, "Run command failed\n");
        goto cleanup;
    }

    writeTest("Disassembling bytecode");

    snprintf(cmd, sizeof(cmd),
             "%s disassemble %s --hex",
             leyoBin, outputFile);

    if (runCommand(cmd)) {
        fprintf(stderr, "Disassemble command failed\n");
        goto cleanup;
    }

    printf("\n");
    writeTest("Smoke test passed");
    r = 0;

cleanup:
    writeTest("Cleaning Smoke Test");

    if (f)
        fclose(f);

    destroyTmpFolder();
    return r;
}
